# -*- coding: utf-8 -*-
"""DS17 - Programming 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wxknq9k92vjp7A6aRWaVPptdcPu77Ue6
"""

nama = 'Alvin'
umur = 23
tinggi = 171.5

contoh_satu = "Hello every one. I'm Alvin"
contoh_dua = 'Hello every one. I am "Alvin'

#Ini adalah Koleksi di Python

nama_siswa = ['Alvin', 'Wanta', 'Fachri', 'Wahyu', 'Sigit'] #List
nama_nabi_islam = ('Muhammad', 'Adam') #Tuple
info_tentang_indonesia = {'Populasi' : 200000000, 'Ibu Kota' : 'Indonesia', 'Negara Berkembang' : True} #Dictionary

#Fakta List Python

#List bisa menyimpan semua tipe data di dalamnya, sementara bahasa lain tidak bisa
List1 = [True, 12.7, 23, "Alvin", info_tentang_indonesia, nama_siswa]
#kalau di bahasa lain aku disebut sebagai array

# Cara menggunakan List

# 1. Manggil Nilai di List

print(nama_siswa)
print(nama_siswa[0])
print(nama_siswa[2])
print(nama_siswa[4])

print(nama_siswa[-1])
print(nama_siswa[-2])

# 2. Jika datanya banyak, data yang mau dipanggil berada di tengah sedangkan saya gatau data tsb berada diurutan berapa

index = nama_siswa.index('Fachri')
print(index)

print(nama_siswa[index])
print(nama_siswa[2])
print(nama_siswa[nama_siswa.index('Wanta')])

# 3. Nambahin data di list kelas kita pakai append

nama_siswa.append('Fawwaz')
print(nama_siswa)

# 3. Nambahin data di list kelas kita pakai insert

nama_siswa.insert(5, 'Alda')
print(nama_siswa)

# 3. Nambahin data di list kelas kita pakai extend

nama_siswa.extend(['Bambang', 'Joko', 'Basuki'])
print(nama_siswa)

# 4. Menghilangkan data di list pakai pop

nama_siswa.pop()
print(nama_siswa)

# 4. Menghilangkan data di list pakai remove

nama_siswa.remove('Ayu')
print(nama_siswa)

nama_siswa.remove('Fawwaz')
print(nama_siswa)

nama_siswa.remove('Wahyu')
print(nama_siswa)

nama_siswa.remove('Fawwaz')
print(nama_siswa)

nama_siswa.remove('Ayu')
print(nama_siswa)

# Mengurutkan (Sort)

nama_siswa.sort()
print(nama_siswa)

nama_siswa.sort(reverse=True)
print(nama_siswa)

nama_siswa.append('Ayu')
print(nama_siswa)

# 5. Menghitung jumlah elemen yang ada dalam list

nama_siswa.count('Ayu')

# 6. Menghilangkan semua elemen yg ada di dalam list

nama_siswa.clear()
print(nama_siswa)

nama_siswa = ['Wanta', 'Sigit', 'Joko', 'Fawwaz', 'Fachri', 'Bambang', 'Alvin', 'Alda', 'Ayu']

# 7. Cara copy list kita ke list yang lain

# Swallow copy
copy_nama_siswa = nama_siswa
print(copy_nama_siswa)

# Deep copy
deep_copy_nama_siswa = nama_siswa.copy()

info_tentang_indonesia = {'Populasi' : 200000000, 'Ibu Kota' : 'Indonesia', 'Negara Berkembang' : True}

# Dictionary
info_tentang_indonesia['Populasi']

# 1. Memanggil semua key yang ada dalam dictionary kita
info_tentang_indonesia.keys()

# 2. Memanggil semua items yang ada dalam dictionary kita
info_tentang_indonesia.items()
print(info_tentang_indonesia.items())
print(info_tentang_indonesia)

# 3. Memanggil semua values yang ada dalam dictionary kita
info_tentang_indonesia.values()

# 4. Get
info_tentang_indonesia.get('Populasi')

# Tuple
nama_nabi_islam = ('Muhammad', 'Adam')
nama_nabi_islam[0]

# Konversi
nama_nabi_islam = list(nama_nabi_islam)
print(nama_nabi_islam)
nama_nabi_islam = tuple(nama_nabi_islam)

# Kondisi
x = 10
y = 20

if x<y:
  print('Nilai x lebih kecil daripada y')

print('Aku ada diluar if dan aku selalu ter-print')

# Kondisi
x = 20
y = 20

if x<y:
  print('Nilai x lebih kecil daripada y')  #kalo if nya gacocok, ini gabakal ke print
elif x>y:
  print('Nilai x lebih besar daripada y')
else:
  print('Nilai x sama dengan y')
print('Aku ada diluar if dan aku selalu ter-print')

nama = 'Alvin'

if nama == 'Joko':
  print('Orangnya Tampan')
elif nama == 'Cika':
  print('Orangnya cantik')
elif nama == 'Bambang':
  print('Orangnya lucu')
else:
  print('Orangnya biasa ajah')

# Looping

i = 0
while i < 10:
  print('Alvin')
  i += 1 # sama kayak i = i + 1

